Repository LonelyIslet/TheJulge, pull requests merged in 2023-07, with the labels that each got.

#6 JUL-84/feature/StatusChip
  app/kenny/page.tsx
  components/common/StatusChip/StatusChip.module.scss
  components/common/StatusChip/StatusChip.tsx
  styles/mixins.scss
  styles/variables.scss
  types/enums/apply.enum.ts
Labels: enhancement

#7 JUL-37/pagination
  README.md
  components/common/NavBar/NavBar.module.scss
  components/common/Pagination/Pagination.module.scss
  components/common/Pagination/Pagination.tsx
  components/common/SearchBar/SearchBar.module.scss
  components/common/index.ts
  next.config.js
Labels: enhancement

#9 JUL-40/feature/PostCard
  .eslintrc.json
  README.md
  app/tina/page.tsx
  components/common/HourlyPayPercentage/HourlyPayPercentage.module.scss
  components/common/HourlyPayPercentage/HourlyPayPercentage.tsx
  components/common/PostCard/PostCard.module.scss
  components/common/PostCard/PostCard.tsx
  components/common/index.ts
  constants/mock/notice.json
  next.config.js
  package-lock.json
  package.json
  public/images/arrow-gray.svg
  public/images/arrow-red-20.svg
  public/images/arrow-red-30.svg
  public/images/arrow-red-40.svg
  public/images/arrow-red-primary.svg
  public/images/arrow-white.svg
  public/images/clock-gray.svg
  public/images/clock-red.svg
  public/images/location-gray.svg
  public/images/location-red.svg
  styles/variables.scss
  utils/calculatePercentage.ts
  utils/formatTimeRange.ts
Labels: enhancement

#8 JUL-43/feature/Modals
  app/kenny/page.tsx
  app/layout.tsx
  components/common/Modal/Modal.module.scss
  components/common/Modal/Modal.tsx
  components/common/Modal/ModalPortal.tsx
  components/common/index.ts
  types/enums/modal.enum.ts
Labels: enhancement

#15 JUL-51/feature/LoginPage
  app/auth/page.module.scss
  app/auth/page.scss
  app/auth/page.tsx
  app/kenny/page.module.scss
  app/kenny/page.tsx
  components/auth/AuthForm/AuthForm.module.scss
  components/auth/AuthForm/AuthForm.tsx
  components/auth/AuthForm/SigninForm.tsx
  components/auth/AuthForm/SignupForm.tsx
  components/auth/AuthForm/UserTypeSelect.module.scss
  components/auth/AuthForm/UserTypeSelect.tsx
  components/auth/LoginForm/Login.tsx
  components/auth/index.ts
  components/common/GlobalNav/GlobalNav.module.scss
  components/common/GlobalNav/GlobalNav.tsx
  public/images/landing-img.png
  public/images/logo-white.svg
  public/sitemap-0.xml
  styles/globals.scss
  types/enums/user.enum.ts
Labels: enhancement

#18 JUL-44/feature/Toast
  .eslintrc.json
  app/auth/page.tsx
  app/kenny/page.tsx
  app/layout.tsx
  components/common/Toast/Toast.module.scss
  components/common/Toast/Toast.tsx
  components/common/Toast/ToastPortal.tsx
  components/common/Toast/ToastRoot.tsx
  components/common/index.ts
  hooks/useSample.ts
  hooks/useToast.ts
  redux/slices/sampleSlice.ts
  redux/slices/toastSlice.ts
  redux/store.ts
Labels: enhancement

#20 JUL-41/feature/NotificationPopover
  README.md
  app/kenny/page.tsx
  components/common/NotificationBoard/NotificationBoard.module.scss
  components/common/NotificationBoard/NotificationBoard.tsx
  components/common/Popover/Popover.tsx
  components/common/StatusChip/StatusChip.module.scss
  components/common/StatusChip/StatusChip.tsx
  components/common/index.ts
  constants/mock/alerts.json
  hooks/useClickOutside.ts
  styles/mixins.scss
  types/dto.ts
  types/enums/apply.enum.ts
  utils/formatTimeRange.ts
  utils/showElapsedTime.ts
Labels: enhancement

#23 JUL-42/Filter 컴포넌트
  .eslintrc.json
  README.md
  app/layout.tsx
  app/my-profile/edit/page.tsx
  app/my-profile/layout.tsx
  app/page.tsx
  app/tony/page.tsx
  components/auth/AuthForm/SigninForm.tsx
  components/auth/AuthForm/SignupForm.tsx
  components/auth/AuthForm/UserTypeSelect.tsx
  components/common/CommonDetail/CommonDetail.tsx
  components/common/CommonLayout/CommonLayout.tsx
  components/common/CustomInput/UserInput.tsx
  components/common/Dropdown/Dropdown.module.scss
  components/common/Dropdown/Dropdown.tsx
  components/common/Filter/Filter.module.scss
  components/common/Filter/Filter.tsx
  components/common/GlobalNav/GlobalNav.tsx
  components/common/Modal/ModalPortal.tsx
  components/common/NotificationBoard/NotificationBoard.module.scss
  components/common/NotificationBoard/NotificationBoard.tsx
  components/common/Pagination/Pagination.module.scss
  components/common/Pagination/Pagination.tsx
  components/common/Popover/Popover.tsx
  components/common/PostCard/CustomArrow/CustomArrow.tsx
  components/common/PostCard/PostCard.tsx
  components/common/ShopCard/ShopCard.tsx
  components/common/StatusChip/StatusChip.tsx
  components/common/Table/Table.module.scss
  components/common/Table/Table.tsx
  components/common/Toast/Toast.tsx
  components/common/Toast/ToastPortal.tsx
  components/common/Toast/ToastRoot.tsx
  components/common/index.ts
  components/employee/EditProfile/EditProfile.tsx
  components/notice/EmployeeTable/EmployeeTable.tsx
  components/notice/EmployerTable/EmployerTable.tsx
  components/notice/index.ts
  constants/notice/address.ts
  constants/sample.ts
  public/sitemap-0.xml
  styles/globals.scss
  styles/mixins.scss
  types/sample.d.ts
  utils/addCommasToString.ts
  utils/sample.ts
Labels: 🚀 feature

#27 Jul-97/CardList 컴포넌트 제작 및 PostCard, NoticeCard, ShopCard 반응형 ui 적용
  app/my-shop/page.tsx
  app/tina/page.tsx
  components/common/CardList/CardList.module.scss
  components/common/CardList/CardList.tsx
  components/common/CommonBtn/CommonBtn.module.scss
  components/common/CommonLayout/CommonLayout.module.scss
  components/common/NoticeCard/NoticeCard.module.scss
  components/common/NoticeCard/NoticeCard.tsx
  components/common/PostCard/PostCard.module.scss
  components/common/PostCard/PostCard.tsx
  components/common/ShopCard/ShopCard.module.scss
  components/common/ShopCard/ShopCard.tsx
  components/common/index.ts
  constants/mock/noticeList.json
  styles/mixins.scss
Labels: 🚀 feature

#25 JUL-68/내 프로필과 신청 내역 컴포넌트를 적용한 알바생 상세 페이지 구현
  app/my-profile/layout.tsx
  app/my-profile/page.module.scss
  app/my-profile/page.tsx
  components/common/CommonDetail/CommonDetail.module.scss
  components/common/CommonDetail/CommonDetail.tsx
  components/common/CommonLayout/CommonLayout.module.scss
  components/common/Table/Table.module.scss
  components/employee/RegisteredMyProfile/RegisteredMyProfile.module.scss
  components/employee/RegisteredMyProfile/RegisteredMyProfile.tsx
  public/images/phone.svg
  styles/mixins.scss
  types/enums/detailPage.enum.ts
Labels: 🚀 feature

#28 JUL-46/공고리스트 페이지 UI
  README.md
  app/auth/page.tsx
  app/kenny/page.tsx
  app/my-profile/edit/page.tsx
  app/my-profile/page.tsx
  app/page.module.scss
  app/page.tsx
  app/tina/page.tsx
  app/tony/page.tsx
  components/auth/AuthForm/AuthForm.tsx
  components/common/CardList/CardList.tsx
  components/common/CustomInput/UserInput.tsx
  components/common/Dropdown/Dropdown.tsx
  components/common/Filter/Filter.module.scss
  components/common/Filter/Filter.tsx
  components/common/GlobalFooter/GlobalFooter.tsx
  components/common/GlobalNav/GlobalNav.module.scss
  components/common/GlobalNav/GlobalNav.tsx
  components/common/Modal/Modal.tsx
  components/common/NotificationBoard/NotificationBoard.tsx
  components/common/Popover/Popover.tsx
  components/common/PostCard/PostCard.tsx
  components/common/SearchBar/SearchBar.tsx
  components/common/Table/Table.tsx
  components/notice/EmployeeTable/EmployeeTable.tsx
  components/notice/EmployerTable/EmployerTable.tsx
  components/notice/FilterButton/FilterButton.module.scss
  components/notice/FilterButton/FilterButton.tsx
  components/notice/SortButton/SortButton.module.scss
  components/notice/SortButton/SortButton.tsx
  components/notice/SortButton/SortDropdown/SortDropdown.module.scss
  components/notice/SortButton/SortDropdown/SortDropdown.tsx
  components/notice/index.ts
  constants/notice/addresses/ADDRESS_1.ts
  constants/notice/index.ts
  constants/notice/options/SORT_OPTIONS.ts
  constants/notice/table.ts
  constants/notice/tables/EMPLOYEE_COLUMNS.ts
  constants/notice/tables/EMPLOYER_COLUMNS.ts
  hooks/useOutsideClick.ts
  public/sitemap-0.xml
  types/notice/options.ts
  types/notice/tables.ts
Labels: 🚀 feature

#32 JUL-89/인증 기능 추가
  app/auth/page.module.scss
  app/auth/page.scss
  app/auth/page.tsx
  app/kenny/page.tsx
  app/layout.tsx
  components/auth/AuthForm/AuthForm.module.scss
  components/auth/AuthForm/AuthForm.tsx
  components/auth/AuthForm/SigninForm.tsx
  components/auth/AuthForm/SignupForm.tsx
  components/auth/AuthForm/UserTypeSelect.tsx
  components/auth/PersistGateContext/PersistGateContext.tsx
  components/common/GlobalNav/GlobalNav.module.scss
  components/common/GlobalNav/GlobalNav.tsx
  components/common/Loader/Loader.module.scss
  components/common/Loader/Loader.tsx
  components/common/Modal/Modal.tsx
  components/common/index.ts
  constants/auth/user.ts
  next.config.js
  package-lock.json
  package.json
  public/images/close-eye.svg
  public/images/open-eye.svg
  redux/api/authApi.ts
  redux/slices/userSlice.ts
  redux/store.ts
  types/dto.ts
  types/enums/user.enum.ts
  utils/predicateErrorType.ts
Labels: 🚀 feature

#33 Jul 101/feature/드롭다운 유효성 검사 추가
  app/tony/page.tsx
  components/common/Dropdown/Dropdown.module.scss
  components/common/Dropdown/Dropdown.tsx
Labels: 🚀 feature

#29 Jul 77/feature/notice 페이지 UI 제작
  app/my-profile/page.tsx
  app/notice/layout.tsx
  app/notice/page.module.scss
  app/notice/page.tsx
  components/common/CommonDetail/CommonDetail.tsx
  components/common/CommonShopDescription/CommonShopDescription.tsx
  components/common/index.ts
  components/employee/ApplicationDetails/ApplicationDetails.tsx
  components/employee/EditProfile/EditProfile.tsx
  components/employee/EmployeeNotice/EmployeeNotice.tsx
  components/employee/index.ts
  components/employer/EmployerNotice/EmployerNotice.tsx
  components/employer/index.ts
  types/enums/detailPage.enum.ts
Labels: 🚀 feature

#31 Jul 100/feature/가게등록 페이지 제작
  app/notice/write/layout.tsx
  app/notice/write/page.module.scss
  app/notice/write/page.tsx
  components/employer/EditNoticeForm/EditNoticeForm.module.scss
  components/employer/EditNoticeForm/EditNoticeForm.tsx
  components/employer/index.ts
Labels: 🚀 feature

#34 Jul 103/feature/내 프로필 페이지 유효성 검사 구현
  app/my-profile/edit/page.module.scss
  app/tony/page.tsx
  components/auth/AuthForm/SigninForm.tsx
  components/auth/AuthForm/SignupForm.tsx
  components/common/CustomInput/CustomInput.tsx
  components/common/CustomInput/UserInput.tsx
  components/common/Dropdown/Dropdown.module.scss
  components/common/Dropdown/Dropdown.tsx
  components/employee/EditProfile/EditProfile.module.scss
  components/employee/EditProfile/EditProfile.tsx
  constants/dropdown/dropdownData.ts
  hooks/useInputValidation.ts
  types/enums/inputValidation.enum.ts
  utils/inputValidation.ts
Labels: 🚀 feature

#41 JUL-60/무한 캐러셀 구현 및 맞춤공고 컴포넌트 추가
  app/kenny/page.tsx
  app/page.module.scss
  app/page.tsx
  components/common/CommonLayout/CommonLayout.module.scss
  components/common/CommonLayout/CommonLayout.tsx
  components/common/InfiniteCarousel/InfiniteCarousel.module.scss
  components/common/InfiniteCarousel/InfiniteCarousel.tsx
  components/common/InfiniteCarousel/ItemFrame.tsx
  components/common/PostCard/PostCard.module.scss
  components/common/Spinner/Spinner.module.scss
  components/common/Spinner/Spinner.tsx
  components/common/StatusChip/StatusChip.module.scss
  components/common/StatusChip/StatusChip.tsx
  components/common/Table/Table.tsx
  components/common/Twiggler/Twiggler.module.scss
  components/common/Twiggler/Twiggler.tsx
  components/common/index.ts
  components/employee/ApplicationDetails/ApplicationDetails.tsx
  components/employer/EmployerNotice/EmployerNotice.tsx
  components/notice/RecommendedNoticeList/RecommendedNoticeList.module.scss
  components/notice/RecommendedNoticeList/RecommendedNoticeList.tsx
  components/notice/index.ts
  constants/mock/noticeList.json
  hooks/api/auth/useSignup.ts
  hooks/useDisableDraggableChildren.ts
  hooks/useMediaQuery.ts
  package-lock.json
  package.json
  public/images/next-button.svg
  public/images/prev-button.svg
  public/sitemap-0.xml
  redux/api/applicationApi.ts
  redux/api/noticeApi.ts
  styles/globals.scss
  tsconfig.json
  types/dto.ts
  types/notice/tables.ts
Labels: 🚀 feature

#37 Jul 105/feature/공고 등록 유효성 검사 기능 추가
  components/common/CustomInput/CustomInput.module.scss
  components/employer/EditNoticeForm/EditNoticeForm.module.scss
  components/employer/EditNoticeForm/EditNoticeForm.tsx
  hooks/useInputValidation.ts
  types/enums/inputValidation.enum.ts
  utils/inputValidation.ts
Labels: 🚀 feature

#40 Jul 64/feature/MyProfile 유효성 검사 및 회원별 분기 처리 기능 추가
  app/my-profile/page.tsx
  components/common/CustomInput/CustomInput.module.scss
  components/common/CustomInput/CustomInput.tsx
  components/common/CustomInput/UserInput.tsx
  components/common/Dropdown/Dropdown.module.scss
  components/common/Dropdown/Dropdown.tsx
  components/common/InputNumber/InputNumber.tsx
  components/employee/EditProfile/EditProfile.tsx
  components/employee/RegisteredMyProfile/RegisteredMyProfile.tsx
  components/employer/EditNoticeForm/EditNoticeForm.tsx
  hooks/useInputValidation.ts
Labels: 🚀 feature

#42 JUL-108/Protected Route를 위한 HOC 추가
  app/my-profile/edit/page.tsx
  app/my-profile/page.tsx
  app/my-shop/page.tsx
  app/signout/page.tsx
  components/auth/AuthForm/SigninForm.tsx
  components/common/CommonLayout/CommonLayout.module.scss
  components/common/CommonLayout/CommonLayout.tsx
  components/common/GlobalNav/GlobalNav.module.scss
  components/common/GlobalNav/GlobalNav.tsx
  components/hocs/index.ts
  components/hocs/withAuth/withAuth.tsx
  components/hocs/withUserType/withUserType.tsx
  components/notice/RecommendedNoticeList/RecommendedNoticeList.tsx
  hooks/api/image/usePostImageName.ts
  hooks/api/user/useLazyGetUserInfo.ts
  hooks/useToast.ts
  redux/api/imageApi.ts
Labels: 🚀 feature

#44 JUL-108/복원을 위한 PR
  .gitignore
  app/my-profile/edit/page.tsx
  app/my-profile/page.tsx
  app/my-shop/page.tsx
  app/signout/page.tsx
  components/auth/AuthForm/SigninForm.tsx
  components/common/CommonLayout/CommonLayout.module.scss
  components/common/CommonLayout/CommonLayout.tsx
  components/common/GlobalNav/GlobalNav.module.scss
  components/common/GlobalNav/GlobalNav.tsx
  components/hocs/index.ts
  components/hocs/withAuth/withAuth.tsx
  components/hocs/withUserType/withUserType.tsx
  components/notice/RecommendedNoticeList/RecommendedNoticeList.tsx
  hooks/api/image/usePostImageName.ts
  hooks/api/user/useLazyGetUserInfo.ts
  hooks/useToast.ts
  redux/api/imageApi.ts
Labels: 🚑 hotfix

#30 JUL-97/feature/가게 상세 페이지,가게 등록 페이지 제작
  app/my-shop/edit/page.module.scss
  app/my-shop/edit/page.tsx
  app/my-shop/layout.tsx
  app/my-shop/page.module.scss
  app/my-shop/page.tsx
  components/common/CommonDetail/CommonDetail.tsx
  components/common/CustomInput/CustomInput.tsx
  components/common/CustomInput/UserInput.tsx
  components/common/Dropdown/Dropdown.tsx
  components/common/InputNumber/InputNumber.tsx
  components/common/PostCard/PostCard.module.scss
  components/common/PostCard/PostCard.tsx
  components/employer/FileUploater/FileUploader.module.scss
  components/employer/FileUploater/FileUploader.tsx
  components/employer/MyNotice/MyNotice.tsx
  components/employer/MyShop/MyShop.tsx
  components/employer/index.ts
  hooks/useInputValidation.ts
  public/images/camera-gray.svg
  public/images/camera-white.svg
  types/enums/detailPage.enum.ts
Labels: 🚀 feature

#46 JUL-106/feature/최근에 본 공고 기능 추가
  app/tina/page.tsx
  app/tony/page.tsx
  components/common/CommonShopDescription/CommonShopDescription.tsx
  components/common/PostCard/PostCard.tsx
  components/employee/ApplicationDetails/ApplicationDetails.tsx
  components/employee/EmployeeNotice/EmployeeNotice.tsx
  components/notice/RecommendedNoticeList/RecommendedNoticeList.tsx
  redux/slices/userSlice.ts
  types/dto.ts
Labels: 🚀 feature

#47 JUL-111/유저 알림 polling 및 읽음 처리 기능 추가
  app/kenny/page.tsx
  components/common/GlobalNav/GlobalNav.module.scss
  components/common/GlobalNav/GlobalNav.tsx
  components/common/GlobalNav/NotificationButton.module.scss
  components/common/GlobalNav/NotificationButton.tsx
  components/common/NotificationBoard/NotificationBoard.module.scss
  components/common/NotificationBoard/NotificationBoard.tsx
  components/hocs/withAuth/withAuth.tsx
  hooks/api/notice/usePostNotice.ts
  redux/api/noticeApi.ts
Labels: 🚀 feature

#48 JUL-113/로그인 로딩 컴포넌트 추가
  app/signout/page.tsx
  components/auth/AuthForm/SigninForm.tsx
  components/auth/SigninProcess/SigninProcess.module.scss
  components/auth/SigninProcess/SigninProcess.tsx
  hooks/api/user/useLazyGetUserInfo.ts
Labels: 🚀 feature

#50 JUL-114/맞춤공고 없을 때 보여질 디폴트 UI 및 공고카드 툴팁 기능 추가
  components/common/PostCard/PostCard.module.scss
  components/common/PostCard/PostCard.tsx
  components/common/Tooltip/Tooltip.module.scss
  components/common/Tooltip/Tooltip.tsx
  components/notice/RecommendedNoticeList/DefaultRecommendedList.module.scss
  components/notice/RecommendedNoticeList/DefaultRecommendedList.tsx
  components/notice/RecommendedNoticeList/RecommendedNoticeList.module.scss
  components/notice/RecommendedNoticeList/RecommendedNoticeList.tsx
Labels: 🚀 feature

#49 Jul 74/feature/공고등록/편집 api 기능 추가
  app/shops/[shopId]/notices/[noticeId]/page.module.scss
  app/shops/[shopId]/notices/[noticeId]/page.tsx
  components/common/CommonLayout/CommonLayout.module.scss
  components/common/InputNumber/InputNumber.tsx
  components/employer/EditNoticeForm/EditNoticeForm.tsx
  components/employer/EmployerNotice/EmployerNotice.tsx
  components/notice/CheckStatusButton/CheckStatusButton.module.scss
  components/notice/CheckStatusButton/CheckStatusButton.tsx
  components/notice/index.ts
  hooks/api/application/useAcceptApplication.ts
  hooks/api/application/useCancelApplication.ts
  hooks/api/application/useRejectApplication.ts
  hooks/api/notice/usePostNotice.ts
  hooks/api/notice/useUpdateNotice.ts
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  redux/api/applicationApi.ts
  redux/api/noticeApi.ts
  utils/fomattingStringToDate.ts
  utils/formattingData.ts
  utils/formattingStringTonumber.ts
Labels: 🚀 feature

#53 Jul 99/feature/내 가게 상세, 등록 페이지
  .eslintrc.json
  app/my-shop/edit/page.tsx
  app/my-shop/page.module.scss
  app/my-shop/page.tsx
  components/common/CardList/CardList.tsx
  components/common/CommonBtn/CommonBtn.module.scss
  components/common/CommonDetail/CommonDetail.tsx
  components/common/Dropdown/Dropdown.tsx
  components/common/PostCard/PostCard.module.scss
  components/common/ShopCard/ShopCard.module.scss
  components/common/ShopCard/ShopCard.tsx
  components/employer/FileUploater/FileUploader.module.scss
  components/employer/FileUploater/FileUploader.tsx
  components/employer/MyNotice/MyNotice.tsx
  components/employer/MyShop/MyShop.tsx
  hooks/api/shop/usePostShop.ts
  hooks/api/shop/useUpdateShop.ts
  redux/api/imageApi.ts
  redux/api/noticeApi.ts
  redux/slices/userSlice.ts
Labels: 🚀 feature

#54 Jul 116/feature/분기 처리에 따른 공고 버튼 변경
  app/shops/[shopId]/notices/[noticeId]/page.tsx
  components/common/CommonShopDescription/CommonShopDescription.tsx
  types/dto.ts
Labels: 🚀 feature
